---
abstract: 'Dynamic definition of a DBIx::Class::Schema and a DBICx::Modeler'
author:
  - 'MORIYA Masaki, alias Gardejo <moriya at cpan dot org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Class: 0.34
  Test::Exception: 0.27
  Test::More: 0
  Test::Requires: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBICx::Modeler::Generator
name: DBICx-Modeler-Generator
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  DBD::SQLite: 1.26_06
  DBD::mysql: 0
  MooseX::Getopt: 0
  MooseX::SimpleConfig: 0
requires:
  Class::Unload: 0
  DBICx::Modeler: 0.005
  DBIx::Class::Schema::Loader: 0
  File::Find::Rule: 0
  List::MoreUtils: 0
  Module::Load: 0
  Moose: 0.89_01
  MooseX::Types::Path::Class: 0
  Orochi: 0
  Text::MicroTemplate::Extended: 0
  namespace::clean: 0.08
  perl: 5.8.1
resources:
  homepage: http://github.com/gardejo/p5-dbicx-modeler-generator
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gardejo/p5-dbicx-modeler-generator.git
version: 0.02
